#include <stdio.h>
int main()
{
    int n,i,m,j,k,x[10000],l,count;
    scanf("%d",&n);
    for(i=1;i<=n;i++)
    {
        scanf("%d",&m);
        for(j=1;j<=m;j++)
        {
            count=0;
            if(j==1)
            {
                x[j]=++count;
            }
             if(j==2)
            {
               x[j]=++count;
            }
             if(j==3)
            {
                x[j]=++count;
            }
             if(j==4)
            {
               x[j]=++count;
            }
             if(j==5)
            {
                x[j]=++count;
            }
             if(j==6)
            {
               x[j]=++count;
            }
             if(j==7)
            {
                x[j]=++count;
            }
             if(j==8)
            {
                x[j]=++count;
            }
             if(j==9)
            {
               x[j]=++count;
            }
             if(j>9)
            {
               for(k=j;k!=0;k=k/10)
               {
                   l=k%10;
                   count=0;
                   if(l==0)
                   {
                        x[0]+=++count;

                   }
                   if(l==1)
                    {
                        x[1]+=++count;
                    }
                    if(l==2)
                    {
                       x[2]+=++count;
                    }
                    if(l==3)
                    {
                        x[3]+=++count;
                    }
                    if(l==4)
                    {
                       x[4]+=++count;
                    }
                    if(l==5)
                    {
                        x[5]+=++count;
                    }
                    if(l==6)
                    {
                        x[6]+=++count;
                    }
                    if(l==7)
                    {
                        x[7]+=++count;
                    }
                    if(l==8)
                    {
                       x[8]+=++count;
                    }
                    if(l==9)
                    {
                       x[9]+=++count;
                    }

               }
            }

        }
        printf("%d %d %d %d %d %d %d %d %d %d\n",x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7],x[8],x[9]);
        x[0]=0,x[1]=0,x[2]=0,x[3]=0,x[4]=0,x[5]=0,x[6]=0,x[7]=0,x[8]=0,x[9]=0;
    }
    return 0;
}
